In [2]:
import numpy as np

In [184]:
class Softmax:
    def __init__(self):
      """ Softmax is an activation function that transforms
      vector of real numbers into probability distribution """
      pass
  
    def forward(self, X):
        return self._softmax(X)
  
    def backward(self, Z):
        print(Z.shape)
        logits = self.forward(Z)
        n, l = logits.shape
        
        Jac = np.zeros((n, l, l))
        for k in range(n):
            for i in range(l):
                for j in range(l):
                    if i == j:
                        Jac[k, i,j] = logits[k, i] * (1 - logits[k, i])
                    else:
                        Jac[k, i,j] = - logits[k, i] * logits[k, j]
        return Jac
    
    def _softmax(self, v, scale=True):
        if scale:
            v -= np.max(v)
        return (np.exp(v).T / np.exp(v).sum(axis=1)).T

In [189]:
def softmax(z):
    z -= np.max(z)
    sm = (np.exp(z).T / np.sum(np.exp(z), axis=0)).T
    return sm

In [190]:
softmax(np.array([[1, 2, 3],
                  [4, 5, 6]]))

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [185]:
v = np.array([[1, 2, 3]])

In [186]:
Softmax().forward(v)

array([[0.09003057, 0.24472847, 0.66524096]])

In [187]:
Softmax().backward(v)

(1, 3)


array([[[ 0.08192507, -0.02203304, -0.05989202],
        [-0.02203304,  0.18483645, -0.1628034 ],
        [-0.05989202, -0.1628034 ,  0.22269543]]])

In [188]:
Softmax().forward(np.array([[1, 2, 3],
                            [6, 2, 1]]))

array([[0.09003057, 0.24472847, 0.66524096],
       [0.97555875, 0.01786798, 0.00657326]])

In [114]:
y = np.array([[1, 0, 0]])

In [115]:
Softmax().backward(np.array([[100, 200, 300]])) @ y.T

(1, 3)


array([[[ 1.38389653e-087],
        [-5.14820022e-131],
        [-1.38389653e-087]]])

In [134]:
Softmax().forward(np.array([[0.0001, 0.1, 0.3],
                            [0.001, 0.1, 0.3]]))

array([[0.14470798, 0.15991106, 0.19531581],
       [0.14483828, 0.15991106, 0.19531581]])

In [129]:
class CrossEntropy:
    def forward(self, Y, Y_pred):
        return -(Y * np.log(np.clip(Y_pred, 1e-12, None))).mean()
    
    def backward(self, Y, Y_pred):
        return Y_pred - Y
    
    def __repr__(self):
        return "Binary cross-entropy"

In [130]:
back = CrossEntropy().backward(np.array([[1, 0, 0], [0, 1, 0]]), np.array([[0.4, 0.3, 0.3], [0, .5, .5]]))

In [131]:
back

array([[-0.6,  0.3,  0.3],
       [ 0. , -0.5,  0.5]])

In [132]:
back @ Softmax().backward(np.array([[1, 2, 3]]))

(1, 3)


array([[[-0.07373256,  0.01982974,  0.05390282],
        [-0.01892949, -0.17381992,  0.19274941]]])