In [1]:
import sys
sys.path.append('..')
from nn import *
from viz import plot_history
from tools import train_test_split

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[0, 1],
              [0, 2],
              [1, 3]])

b = BatchNorm()
b._initialize(X.shape)
b.forward_propagate(X)

in_dim= (3, 2)


array([[-1.93185162, -1.93185162],
       [-0.70710677, -0.70710677],
       [ 2.63895839,  2.63895839]])

In [4]:
b.gammas

array([[1.],
       [1.]])

In [5]:
b.betas

array([0, 0])

In [6]:
b.backward_propagate(np.array([[1],
                                [1],
                               [1]]))

input_shape (3, 2) | dZ.shape (3, 1)
dgamma.shape= (2, 1)
self.gammas.shape= (2, 1)


(array([[1., 1.],
        [1., 1.],
        [1., 1.]]), array([[0.33333333, 2.        ]]), array([[1.]]))