In [1]:
import sys
sys.path.append('..')
from nn import *
from viz import plot_history
from tools import train_test_split

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[0, 1],
              [0, 2],
              [1, 3]])

b = BatchNorm()
b._initialize(X.shape)
b.forward_propagate(X)

array([[-0.70710677, -1.22474486],
       [-0.70710677,  0.        ],
       [ 1.41421353,  1.22474486]])

In [4]:
b.gammas

array([1, 1])

In [5]:
b.betas

array([0, 0])

In [6]:
b.backward_propagate(np.array([1, 1]))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)