In [1]:
import sys
sys.path.append('..')
from nn import *
from viz import plot_history
from tools import train_test_split

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[0, 1],
              [0, 2],
              [1, 3]])

b = BatchNorm()
b._initialize(X.shape)
y = b.forward_propagate(X)
b.backward_propagate(y.T)

(array([[-1.01249992e-07, -1.01249992e-07,  2.02499984e-07],
        [-3.37499990e-08,  0.00000000e+00,  3.37499990e-08]]),
 array([[2.99999987, 2.99999993]]),
 array([[2.22044605e-16, 0.00000000e+00]]))

In [4]:
m = NeuralNetwork('binary_crossentropy', 'adam', verbose=True, verbose_step=1)
m.add(Dense(30, 'relu'))
m.add(BatchNorm())
m.add(Dense(1, 'sigmoid'))

In [5]:
X = np.random.randn(1000, 30)
Y = np.random.binomial(1, .5, size=(1000, 1))

In [6]:
m.fit(X, Y, batch_size=32, n_epochs=100, reinitialize=True)

[    1/100]: loss=0.68095 
[    2/100]: loss=0.65852 
[    3/100]: loss=0.62714 
[    4/100]: loss=0.59535 
[    5/100]: loss=0.56421 
[    6/100]: loss=0.53414 
[    7/100]: loss=0.51253 
[    8/100]: loss=0.49299 
[    9/100]: loss=0.47464 
[   10/100]: loss=0.46559 
[   11/100]: loss=0.44728 
[   12/100]: loss=0.43640 
[   13/100]: loss=0.44461 
[   14/100]: loss=0.43027 
[   15/100]: loss=0.44290 
[   16/100]: loss=0.43375 
[   17/100]: loss=0.42188 
[   18/100]: loss=0.46085 
[   19/100]: loss=0.46883 
[   20/100]: loss=0.45820 
[   21/100]: loss=0.48687 
[   22/100]: loss=0.49817 
[   23/100]: loss=0.51335 
[   24/100]: loss=0.54078 
[   25/100]: loss=0.47804 
[   26/100]: loss=0.51825 
[   27/100]: loss=0.51766 
[   28/100]: loss=0.55155 
[   29/100]: loss=0.51332 
[   30/100]: loss=0.51107 
[   31/100]: loss=0.46344 
[   32/100]: loss=0.51537 
[   33/100]: loss=0.51038 
[   34/100]: loss=0.45464 
[   35/100]: loss=0.45104 
[   36/100]: loss=0.54667 
[   37/100]: loss=0.51447 
[

History: epoch|loss

In [7]:
m.layers[1].gammas

array([[2.59710084, 2.45464589, 1.87317133, 2.68688639, 2.64712389,
        2.36976416, 2.70427776, 2.73380745, 2.12671323, 2.76991648,
        2.86989744, 2.77922852, 2.44794904, 2.41728062, 2.61233974,
        2.62451709, 2.12074598, 1.99250797, 2.15363893, 2.57641761,
        2.33674048, 2.79490141, 2.49628351, 2.90693216, 2.85601627,
        2.6414463 , 2.73711393, 2.42949819, 2.93107336, 2.69953227]])